### ISSUE TITLE
Error installing

### ISSUE THREAD

**Issue by RuisSoftware** [GiroudMathias/fivem-esx-js#2]
```
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'i',
1 verbose cli   'fivem-esx-js'
1 verbose cli ]
2 info using npm@6.14.4
3 info using node@v12.16.3
4 verbose npm-session 6f6a10cf52971c34
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 http fetch GET 304 https://registry.npmjs.org/fivem-esx-js 842ms (from cache)
8 silly pacote tag manifest for fivem-esx-js@latest fetched in 851ms
9 timing stage:loadCurrentTree Completed in 878ms
10 silly install loadIdealTree
11 silly install cloneCurrentTreeToIdealTree
12 timing stage:loadIdealTree:cloneCurrentTree Completed in 0ms
13 silly install loadShrinkwrap
14 timing stage:loadIdealTree:loadShrinkwrap Completed in 6ms
15 silly install loadAllDepsIntoIdealTree
16 timing stage:rollbackFailedOptional Completed in 1ms
17 timing stage:runTopLevelLifecycles Completed in 886ms
18 silly saveTree fivem-esx-js@0.1.14
18 silly saveTree +-- @citizenfx/client@1.0.1971-1
18 silly saveTree +-- @citizenfx/server@1.0.1971-1
18 silly saveTree `-- fivem-js@1.3.3
18 silly saveTree   `-- @citizenfx/client@1.0.2312-1
19 verbose stack Error: Refusing to install package with name "fivem-esx-js" under a package
19 verbose stack also called "fivem-esx-js". Did you name your project the same
19 verbose stack as the dependency you're installing?
19 verbose stack
19 verbose stack For more information, see:
19 verbose stack     <https://docs.npmjs.com/cli/install#limitations-of-npms-install-algorithm>
19 verbose stack     at checkSelf (C:\Program Files\nodejs\node_modules\npm\lib\install\validate-args.js:75:14)
19 verbose stack     at Array.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\bind-actor.js:15:8)
19 verbose stack     at LOOP (C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\chain.js:15:14)
19 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\chain.js:18:7
19 verbose stack     at hasMinimumFields (C:\Program Files\nodejs\node_modules\npm\lib\install\validate-args.js:30:12)
19 verbose stack     at Array.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\bind-actor.js:15:8)
19 verbose stack     at LOOP (C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\chain.js:15:14)
19 verbose stack     at chain (C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\chain.js:20:5)
19 verbose stack     at C:\Program Files\nodejs\node_modules\npm\lib\install\validate-args.js:16:5
19 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\async-map.js:52:35
19 verbose stack     at Array.forEach (<anonymous>)
19 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\async-map.js:52:11
19 verbose stack     at Array.forEach (<anonymous>)
19 verbose stack     at asyncMap (C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\async-map.js:51:8)
19 verbose stack     at module.exports (C:\Program Files\nodejs\node_modules\npm\lib\install\validate-args.js:15:3)
19 verbose stack     at Array.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\bind-actor.js:15:8)
20 verbose cwd F:\FiveM\Netherlands\nl_fivem_01\resources\[esx]\[beroepen]\[OV]\fivem-esx-js
21 verbose Windows_NT 10.0.17763
22 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "i" "fivem-esx-js"
23 verbose node v12.16.3
24 verbose npm  v6.14.4
25 error code ENOSELF
26 error Refusing to install package with name "fivem-esx-js" under a package
26 error also called "fivem-esx-js". Did you name your project the same
26 error as the dependency you're installing?
26 error
26 error For more information, see:
26 error     <https://docs.npmjs.com/cli/install#limitations-of-npms-install-algorithm>
27 verbose exit [ 1, true ]
```

Maybe i'm starting the wrong way?

**Comment by daviten74** [comment]
[           resources] Stopping resource 1974_bot
[    c-scripting-core] Creating script environments for 1974_bot
[     script:1974_bot] Error parsing script @1974_bot/index.js in resource 1974_bot: SyntaxError: Cannot use import statement outside a module
[    c-scripting-core] Failed to load script index.js.
[           resources] Started resource 1974_bot
